export enum ErrorMessage {
  //COMMON
  COMMON_BAD_REQUEST = "COMMON_BAD_REQUEST",

  //SOCKET
  CANNOT_CONNECT_TO_SOCKET = 'CANOT_CONNECT_TO_SOCKET',

  //USER
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  //SERVER
  SERVER_NOT_FOUND = "SERVER_NOT_FOUND",

  //SERVER PERMISSION
  SERVER_PERMISSION_NOT_FOUND = "SERVER_PERMISSION_NOT_FOUND",

  //CHANNEL
  CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",
}
